PLANT_ID = "PLT-JUAREZ-01"
LINE_ID = "LINE-1"
LOCATION = "CONVEYOR-1"
PRODUCT = "EJE-TRACCION-2500"
SKU = "SKU-ACERO-M8"
WAREHOUSE = "ALMACEN-MP-01"
SHIFT = "A"

PLAN_ORIGINAL_UNITS = 1200
OEE_BASE = 0.78
AVAILABILITY_BASE = 0.92
PERFORMANCE_BASE = 0.88
QUALITY_BASE = 0.96
PARTS_PER_MIN_MIN = 8
PARTS_PER_MIN_MAX = 18
CYCLE_TIME_MIN = 3.5
CYCLE_TIME_MAX = 7.5

STOCK_INITIAL_MIN = 400
STOCK_INITIAL_MAX = 1200
DAILY_DEMAND_MIN = 180
DAILY_DEMAND_MAX = 320
LEAD_TIME_DAYS_MIN = 2
LEAD_TIME_DAYS_MAX = 5
SAFETY_STOCK_FACTOR = 0.35
UNIT_COST_MXN_MIN = 28
UNIT_COST_MXN_MAX = 42

RISK_THRESHOLD = 0.72
RISK_SCORE_CRITICAL = 75
WINDOW_SIZE = 50

PLATFORM_VERSION = "2.0.0"
MODULE_ERP = "erp_material_planning"
MODULE_PROD = "advanced_production_planning"
MODULE_AIML = "materialflow_intelligence"
MODULE_EDGE = "edge_material_runtime"

CLOUD_DB_PATH = "/tmp/cloud.db"
EDGE_DB_PATH = "/tmp/edge_buffer.db"
